name: "Jenkins-Action"
description: "Start Jenkins jobs and report back URL and status of build"
author: "Coupa Software"
inputs:
  aws_access_key_id:
    description: "AWS Access Key ID"
    required: true
  aws_secret_access_key:
    description: "AWS Secret Access Key"
    required: true
  url:
    description: "Jenkins URL including http/https protocol"
    required: true
  job_name:
    description: "Jenkins job name to build"
    required: true
  username:
    description: "Jenkins username"
    required: false
  api_token:
    description: "Jenkins API token"
    required: false
  parameters:
    description: 'Build parameters in JSON format e.g. `{"field1":"value1"}`'
    required: false
  cookies:
    description: 'Cookies to include in HTTP requests in JSON format e.g. `{"field1":"value1"}`'
    required: false
  wait:
    description: "Should the runner wait for the build to finish and provide ok status"
    required: false
    default: "True"
  timeout:
    description: "Timeout in seconds for build to complete"
    required: false
    default: "600"
  start_timeout:
    description: "Timeout in seconds for build to start"
    required: false
    default: "600"
  interval:
    description: "How frequently in seconds to query Jenkins for build status"
    required: false
    default: "5"
outputs:
  build_url:
    description: "Jenkins build URL"
runs:
  using: "composite"
  steps:
    - name: Log in to Amazon ECR
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 899991151204.dkr.ecr.us-east-1.amazonaws.com

    - name: Pull the docker image
      shell: bash
      run: docker pull 899991151204.dkr.ecr.us-east-1.amazonaws.com/jenkins-githubaction:v1.0.1

    - name: Run Docker container
      shell: bash
      run: docker run jenkins-action
